ECHO Setting PATH Variable.....
set PATH=C:\Program Files\NASM;C:\Perl64\bin;%PATH%
if NOT ["%errorlevel%"]==["0"] pause
ECHO CD To VS.....
cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build" || exit /b
ECHO Setting up VS.....
call vcvars64.bat || exit /b
ECHO CD To OpenSSL.....
cd C:\OpenSSL || exit /b
ECHO using Perl to Configure OpenSSL.....
perl configure VC-WIN64A --prefix=C:\OpenSSL-Win64 || exit /b
ECHO Compileing OpenSSL.....
nmake || exit /b
ECHO Running OpenSSL Tests.....
nmake test || exit /b
ECHO Installing OpenSSL.....
nmake install || exit /b
